### ISSUE TITLE
Compatibility Certification Request for Eclipse Tyrus 2.1.0-M3

### ISSUE THREAD

**Issue by jansupol** [jakartaee/websocket#396]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  Eclipse Tyrus 2.1.0-M3, see TCK Result Summary for the download links
- [x] Specification Name, Version and download URL\
   [Jakarta WebSocket 2.1](https://jakarta.ee/specifications/websocket/2.1/)
- [x]  TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta WebSocket TCK 2.1.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-websocket-tck-2.1.0.zip), SHA-256: 13712800a2dd23b025ccc9cd61604b3292cae6e1035e401ea540e60b18ab3ab0
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/tyrus/tck/eclipse-tyrus-2.1.0-M3)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  JDK 11.0.2+9
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
   Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by jansupol** [comment]
@markt-asf Can you please update https://github.com/jakartaee/specifications/pull/440? Thanks.

**Comment by markt-asf** [comment]
This all looks good to me.
