### ISSUE TITLE
ContainerProvider factory method should be security manager sensitive

### ISSUE THREAD

**Issue by ropalka** [jakartaee/websocket#403]

**Comment by joakime** [comment]
This is inappropriate for Jakarta WebSocket, as Jakarta wide there is a movement to remove all SecurityManager usages in light of the deprecating / neutering / and future removal of the SecurityManager in the JVM.

See:

* https://openjdk.org/jeps/411
* https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/SecurityManager.html

This would be a step backwards for Jakarta as a whole, and the Jakarta Websocket API.

The minimum JVM support level (for TCK compliance) on Jakarta WebSocket is Java 17, which has SecurityManager already removed as well.

**Comment by markt-asf** [comment]
Confirming as WONTFIX since SecurityManager support is being removed across the Jakarta EE platform.
