### ISSUE TITLE
why is websocket no support for cluster?

### ISSUE THREAD

**Issue by snifferhu** [jakartaee/websocket#414]
As we know websocket's session is different from servlet‘s session, it a status server. And servlet is statusless server.
We can not just use a simple session manager server for share status. so I think this is a reason why jakartaee websocket no pupular.

I suggestion is to use a message queue to provide broadcasting or routing capabilities for WebSocket services, or to use a session service to keep track of the connection states of various endpoints for routing purposes.

**Comment by snifferhu** [comment]
why not privder one stander support for cluster

**Comment by joakime** [comment]
There are plenty of libraries built on top of Jakarta WebSocket that provide the features you are looking for.
The low level nature of Jakarta WebSocket Spec is not the place to define this.

The `jakarta.websocket.Session` class represents a single active connected websocket session.

The use of "Session" here is no different than many other uses of the same word elsewhere (eg: "TLS Session") - definition: _a period of time devoted to a particular activity._
The "activity" that `jakarta.websocket.Session` refers to, is the specific WebSocket connection, and it's lifecycle.
The same `jakarta.websocket.Session` is not shared across different connections, even from the same client. (unlike how a Servlet `HttpSession` works).
It could have easily been called `jakarta.websocket.Connection` and had the exact same meaning.
