### ISSUE TITLE
Certification Request: Tomcat-11.0.0-M19-SNAPSHOT for WebSocket 2.2.0

### ISSUE THREAD

**Issue by markt-asf** [jakartaee/websocket#423]
License:
  The terms of the EFTL are acceptable.

Product Name, Version and download URL:
  Apache Tomcat
  11.0.0-M19-SNAPSHOT (build 20240326.151401-23)
  https://repository.apache.org/content/groups/snapshots/org/apache/tomcat/tomcat/11.0.0-M19-SNAPSHOT/tomcat-11.0.0-M19-20240326.151401-23.tar.gz

Specification Name, Version and download URL:
  Jakarta WebSocket
  2.2.0
  https://github.com/jakartaee/specifications/pull/713

TCK Version, digital SHA-512 fingerprint and download URL
  TCK
  2.2.0
  https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-websocket-tck-2.2.0.zip
  SHA512: 3284c6f45193a5f5e34b8bb9c65e222b6a35dd66a9c141466c0e35f36a7fb88ed9f7b498eb2688aa3d5be852a356bfc5165b9c49b5a17331ce99658cf2ad4d31

Implementation runtime Version(s) tested:
  Apache Tomcat
  11.0.0-M19-SNAPSHOT (build 20240326.151401-23)

Public URL of TCK Results Summary:
  https://tomcat.apache.org/tck/websocket-2.2.0-tomcat-11.0.0-M19-SNAPSHOT.txt

Any Additional Specification Certification Requirements:
  None

Java runtime used to run the implementation:
  Java 17 - Temurin 17.0.10
  Java 21 - Temurin 21.0.2

Summary of the information for the certification environment:
  Ubuntu 22.04.4 LTS
​  https://github.com/apache/tomcat-tck
  hash 2c6877326a5b05c24a1b0cc40b801177dfdf8ac7

A statement attesting that all TCK requirements have been met, including any compatibility rules:
  Confirmed

Test results:
  Java 17: Tests run: 737, Failures: 0, Errors: 0, Skipped: 0
  Java 21: Tests run: 737, Failures: 0, Errors: 0, Skipped: 0

**Comment by markt-asf** [comment]
I'm submitting this certification request for 11.0.0-M19-SNAPSHOT so I can progress the WebSocket 2.2.0 release review. I am anticipating submitting a request for 11.0.0-M19 once released.

**Comment by kazumura** [comment]
@markt-asf   
The SHA512 value of the current zip file on the staging repo is different from the one in this CCR.

the current zipfile :  dd24dc092b20e55eda1e939227642d9d4bafc4462de16f647ff4771b08693db201f5bd490cc88956d0c82d31cafb5ce8d7ffdd4f0ec7221bb0d30bb588b4be9d 
CCR: 
3284c6f45193a5f5e34b8bb9c65e222b6a35dd66a9c141466c0e35f36a7fb88ed9f7b498eb2688aa3d5be852a356bfc5165b9c49b5a17331ce99658cf2ad4d31

If you update the TCK zipfile, please also update this CCR with new SHA value and re-run the TCK.

**Comment by gurunrao** [comment]
Websocket TCK needs to be finalized based on:

-  EFTL 1.1 Licensing discussion [ https://github.com/jakartaee/platform-tck/pull/1262#issuecomment-2022327731 ] 
- Publishing of TCK common libraries to maven repository location https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/tck/

**Comment by kazumura** [comment]
@markt-asf   
Could you update CCR with the revised TCK ?
Or if you have any problems with proceeding, please inform.

**Comment by markt-asf** [comment]
I've been on PTO and am currently working through the TODO list that built up while I was away. This is on that TODO list.
