### ISSUE TITLE
Compatibility Certification Request for Eclipse Tyrus 2.2.0-M1 (JDK 21)

### ISSUE THREAD

**Issue by jansupol** [jakartaee/websocket#425]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  Eclipse Tyrus 2.2.0-M1, see TCK Result Summary for the download links
- [x] Specification Name, Version and download URL\
   [Jakarta WebSocket 2.2](https://jakarta.ee/specifications/websocket/2.2/)
- [x]  TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta WebSocket TCK 2.2.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl//jakarta-websocket-tck-2.2.0.zip), SHA-256: ff50825305bd1318a4e6bdfab21b829cfd8cf89fab8a970f007b52636d3f2629
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/tyrus/tck/eclipse-tyrus-2.2.0-M1-jdk21)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  JDK Java version: 21.0.2, vendor: Oracle Corporation, runtime: /opt/tools/java/openjdk/jdk-21/21.0.2
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
   Linux basic-5tzms 6.2.9-300.fc38.x86_64 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by jansupol** [comment]
Updated the CCR to match TCK bundle from 2024-04-08.

**Comment by markt-asf** [comment]
LGTM
