### ISSUE TITLE
Finalize the Jakarta Websocket 2.2 Release

### ISSUE THREAD

**Issue by kazumura** [jakartaee/websocket#428]
Please complete the following steps to complete the release:

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] (N/A) if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by markt-asf** [comment]
Release steps and associated checks completed.
